# server setting
server.port=3888
server.servlet.context-path=/adws
server.logRegion=inner

# disable jmx
spring.jmx.enabled=false

# default connection pool
spring.datasource.hikari.connectionTimeout=10000
spring.datasource.hikari.maximumPoolSize=10

spring.datasource.initialization-mode=never

# JPA
spring.jpa.database=default
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false  
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect

# Postgre Datasource for log
log.datasource.jdbc-url=jdbc:postgresql://10.7.145.114:5432/idmdb
log.datasource.username=postgres
log.datasource.password=1qaz@WSX
log.datasource.driver-class-name=org.postgresql.Driver

# H2 web console setting
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2

# H2 Datasource for oAuth client
#h2.datasource.jdbc-url=jdbc:h2:file:C:/ExCmdService/data/h2
#h2.datasource.username=idmadmin
#h2.datasource.password=1qaz@WSX
#h2.datasource.driver-class-name=org.h2.Driver

# oAuth2
security.oauth2.resource.filter-order=3
