spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/idmdb
    username: exidm
    password: exidm
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  ldap:
    host: 10.254.215.221
    password: "1qaz@WSX"
    port: 636
    secure: true
    username: CN=FIAIDMAdmin2,OU=ServiceAdmin,OU=FIAAccount,OU=ap,DC=fia,DC=gov,DC=tw

activedirectory:
  service:
    placeholder: external
    domaindn: "DC=fia,DC=gov,DC=tw"
    upndomain: "@fia.gov.tw"
    indomaindn: "DC=fia,DC=gov,DC=tw"
    inupndomain: "@fia.gov.tw"
    mofdn: "OU=MOF,DC=fia,DC=gov,DC=tw"
    targetdn: "OU=AHBDE,DC=fia,DC=gov,DC=tw"
    removeuser:
      enabled: true
      maxlimit: 300

exServer_ip: "10.6.241.179:3888"