spring.application.name=ad_pwd_filter
# spring 3 disable security
spring.main.allow-bean-definition-overriding=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# server setting
server.port=3888
server.servlet.context-path=/adws
server.address=127.0.0.1
server.logRegion=inner

# disable jmx
spring.jmx.enabled=false

# default connection pool
spring.datasource.hikari.connectionTimeout=10000
spring.datasource.hikari.maximumPoolSize=10

# initialization mode
spring.sql.init.mode=never

# JPA
spring.jpa.database=default
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Postgre Datasource for log
log.datasource.jdbc-url=jdbc:postgresql://192.168.16.130:5432/idmdb
log.datasource.username=inidm
log.datasource.password=inidm
log.datasource.driver-class-name=org.postgresql.Driver

# Postgre Datasource for web
web.datasource.jdbc-url=jdbc:postgresql://192.168.16.130:5432/idmdb
web.datasource.username=inidm
web.datasource.password=inidm
web.datasource.driver-class-name=org.postgresql.Driver

# H2 web console setting
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# H2 Datasource for oAuth client
h2.datasource.jdbc-url=jdbc:h2:file:C:/AdPwdSync/data/h2
h2.datasource.username=idmadmin
h2.datasource.password=1qaz@WSX
h2.datasource.driver-class-name=org.h2.Driver

# disable liquibase
spring.liquibase.enabled=false

# kms service config
kms.client.jceks.name=adws.jceks
kms.client.jceks.password=1qaz@WSX