# oAuth2 setting
user_name=admin
user_pwd=admin
client_id=exchange_cmd_service_client
client_secret=exchange_cmd_service_secret

# log setting
spring.main.banner-mode=off 
logging.level.root=ERROR
logging.level.com.cht.exchange.commander=TRACE
logging.level.com.cht.exchange.security=TRACE
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level  %class{0}.%M - %msg%n

exServer_ip=127.0.0.1:3888